stages:
- name: Docker
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: bwce-base:2.5.3
      pushRemote: true
timeout: 60
notification:
  recipients:
  - recipient: rancher-notifier
    notifier: c-s5dd6:n-89qlw
  condition:
  - Success
  - Changed
  - Failed
