stages:
- name: Docker
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: bwce-base:2.5.3
      registry: 127.0.0.1:34276
timeout: 60
notification:
  recipients:
  - recipient: rancher-notifier
    notifier: c-s5dd6:n-89qlw
  condition:
  - Success
  - Changed
  - Failed
